baseurl = "http://nitishjadia.com"
title = "Nitish Jadia"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Nitish"
    info = "BackEnd DevOps and Containers"
    description = "Nitish personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/jadia.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jadia/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/nitishjadia/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/jadianitish/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "http://jadia.dev"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
